### ISSUE TITLE
Explanation??

### ISSUE THREAD

**Issue by SamMo00** [SamMo00/Problem#2]

**Comment by Moataz-Elmesmary** [comment]
In the code, we are getting the current element by lst[i]. Then we create the remaining list by lst[:i] + lst[i+1:]

We stored it in the remaining list named as rem_list. After that, we recursively call the get_permutation. This will give permutation for the rest elements. We stored that in the rem_perm list.

Finally, we have to join the current element with the rest of the list. To do so, we have added [current] + p

The loop variable p is a list. Whereas the current is an element. You can not add

3 + [2,1]

That’s why we put current in a list as well so that it becomes a list as well. In the following example,

[3] + [2, 1]

This will create [3, 2, 1]. That’s why we did [current] + p to make the final permutation.

**Comment by SamMo00** [comment]
this is v helpful
